Introduction to Matrices - multidimensional array, essentially an array of arrays

In [1]:
import numpy as np

In [2]:
# create a 2 x 2 array
two_by_two = np.matrix(
                       [[1, 2],
                        [3, 4]]
                      )
print(two_by_two)

[[1 2]
 [3 4]]


In [20]:
# if arrays are not same size the arrays will be converted to an array of lists
two_by_three = np.matrix([[1, 2], [3, 4, 5], [6, 7]])
print(two_by_three)

[[list([1, 2]) list([3, 4, 5]) list([6, 7])]]


In [8]:
# create a 2 x 3 matrix
two_by_three = np.matrix('1 2; 3 4; 5 6')
print(two_by_three)
print("# ====================================== #")
# create a 3 x 4 matrix
three_by_four = np.matrix('0 0 0; 0 1 0; 0 1 0; 0 1 0')
print(three_by_four)

[[1 2]
 [3 4]
 [5 6]]
# ====================================== #
[[0 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]


In [25]:
# create a matix to represent a number 1
print("# ====================================== #")
num_one = np.matrix('0 0 1 0 0; 0 1 1 0 0; 1 1 1 1 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 0 0 1 0 0; 1 1 1 1 1')
print(num_one)
print("# ====================================== #")

# ====================================== #
[[0 0 1 0 0]
 [0 1 1 0 0]
 [1 1 1 1 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]]
# ====================================== #


In [26]:
print(np.zeros([3, 2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
print(np.ones([10, 20]))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
# create a matix to represent a number 2
print("# ====================================== #")
num_two = np.matrix('0 0 1 0 0; 0 1 1 1 0; 1 0 0 0 1; 0 0 0 0 1; 0 0 0 0 1; 0 0 0 1 0; 0 0 1 0 0; 0 1 1 0 0; 1 1 1 1 1')
print(num_two)
print("# ====================================== #")

# ====================================== #
[[0 0 1 0 0]
 [0 1 1 1 0]
 [1 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 1 0 0]
 [1 1 1 1 1]]
# ====================================== #
