# Functions to get elements or properties of matrices

In [1]:
import numpy as np

In [2]:
a_matrix = np.matrix(
                     [
                         [1, 2, 3], 
                         [4, 5, 6], 
                         [7, 8, 9]
                     ])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("# -------------------------------------- #")
print(a_matrix[0])
print("# -------------------------------------- #")
print(a_matrix[1])
print("# -------------------------------------- #")
print(a_matrix[2])
print("# -------------------------------------- #")

# -------------------------------------- #
[[1 2 3]]
# -------------------------------------- #
[[4 5 6]]
# -------------------------------------- #
[[7 8 9]]
# -------------------------------------- #


In [14]:
# print value in 1st array, 2nd position
print(a_matrix[0,1])
# print value in 3rd array, 3rd position
print(a_matrix[2,2])
# print value in 2nd array, 1st position
print(a_matrix[1,0])

2
9
4


In [15]:
# what size is the matrix 3 x 3 = 9
print(a_matrix.size)

9


In [16]:
# what shape is the matrix 3 x 3
print(a_matrix.shape)

(3, 3)


In [17]:
print(np.amax(a_matrix))                # whats the max value 9
print(np.amin(a_matrix))                # whats the min value 1
print(np.average(a_matrix))             # whats the average   5

9
1
5.0


In [20]:
print(a_matrix.max())                   # the max value = 9
print(a_matrix.min())                   # the min value = 1
print(a_matrix.mean())                  # the mean/average = 5

9
1
5.0
