# Functions to modify elements or properties of a matrix

In [1]:
import numpy as np

In [4]:
# initialise the matrix
a_matrix = np.matrix(
                    [
                        [1, 2], 
                        [3, 4]
                    ]
)
print(a_matrix)

[[1 2]
 [3 4]]


In [5]:
a_matrix[1, 0] = 10                # changes 3 to 10
print(a_matrix)

[[ 1  2]
 [10  4]]


In [6]:
a_matrix[0] = [6, 3]              # changes [1, 2] to [6, 3]
print(a_matrix)

[[ 6  3]
 [10  4]]


In [33]:
# initialise the matrix again
a_matrix = np.matrix(
                    [
                        [1, 2], 
                        [3, 4]
                    ]
)
print(a_matrix.T)                        # swap rows and columns
print ("#--------------------------------#")

a_matrix = np.matrix(
                    [
                        [1, 2, 3, 4], 
                        [5, 6, 7, 8], 
                        [9, 10, 11, 12], 
                        [13, 14, 15, 16], 
                    ]
)
print(a_matrix.T)                        # swap rows and columns
print("#--------------------------------#")

[[1 3]
 [2 4]]
#--------------------------------#
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
#--------------------------------#


In [10]:
print(a_matrix.flatten())              # create a single row of values from the rows and columns

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [13]:
print(a_matrix * 2)                    # multiple each value by a factor of 2
print("#--------------------------------#")
print(a_matrix.T * 2)                  # swap rows and columns and then multiple each value by a factor of 2

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
#--------------------------------#
[[ 2 10 18 26]
 [ 4 12 20 28]
 [ 6 14 22 30]
 [ 8 16 24 32]]


In [47]:
x_matrix = [[1,2],[3,4]]                  # b1xa1 + b1*a2 (3) b2xa1 + b2*a2 (3) 
y_matrix = [[1,1],[1,1]]                  # b3xa3 + b1*a4 (7) b4xa3 + b4*a4 (7) 
z_matrix = np.matmul(x_matrix, y_matrix)
print(z_matrix)
print("#----- Add matrix values -------------------------------#")
z_matrix = np.add(x_matrix, y_matrix)
print(z_matrix)


[[3 3]
 [7 7]]
#----- Add matrix values -------------------------------#
[[2 3]
 [4 5]]


In [25]:
x_matrix = [[1,2],[3,4]]                  # b1xa1 + b1*a2 (3) b2xa1 + b2*a2 (6) 
y_matrix = [[1,2],[1,2]]                  # b3xa3 + b1*a4 (7) b4xa3 + b4*a4 (14) 
z_matrix = np.matmul(x_matrix, y_matrix)
print(z_matrix)

[[ 3  6]
 [ 7 14]]


In [52]:
d_matrix = np.matrix([
                     [1, 2, 3, 4],[2, 3, 4, 5],[1, 2, 3, 4],[2, 3, 4, 5]
                     ])  
e_matrix = np.matrix([
                     [1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]
                     ])  
# first row  1*1+1*2+1*3+1*4=10 2*1+2*2+2*3+2*4=20 3*1+3*2+3*3+3*4=30 4*1+4*4+1*4+1*4=40
# second row 1*2+1*3+1*4+1*5=14 2*2+2*3+2*4+2*5=28 3*2+3*3+3*4+3*5=42 4*2+4*3+4*4+4*5=56
# third row  1*1+1*2+1*3+1*4=10 2*1+2*2+2*3+2*4=20 3*1+3*2+3*3+3*4=30 4*1+4*4+1*4+1*4=40
# fourth row 1*2+1*3+1*4+1*5=14 2*2+2*3+2*4+2*5=28 3*2+3*3+3*4+3*5=42 4*2+4*3+4*4+4*5=56

print(d_matrix)
print(e_matrix)
f_matrix=np.matmul(d_matrix, e_matrix)
print(f_matrix)

[[1 2 3 4]
 [2 3 4 5]
 [1 2 3 4]
 [2 3 4 5]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[10 20 30 40]
 [14 28 42 56]
 [10 20 30 40]
 [14 28 42 56]]
