# Example of matrices in action - images

In [1]:
import numpy as np

In [15]:
image_matrix = np.matrix(
    [
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0], 
        [1, 1, 1, 1, 1], 
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0]
    ]
)
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [16]:
# need to get no of rows and number of columns
# .shape returns a tuple (r, c)
rows = image_matrix.shape[0]
cols = image_matrix.shape[1]

print(rows)
print(cols)

5
5


In [19]:
print("#------- BEFORE -------------------------#")
image_matrix = np.matrix(
    [
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0], 
        [1, 1, 1, 1, 1], 
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0]
    ]
)
print(image_matrix)
print("#-------- AFTER ------------------------#")
for r in range(rows):                  # for r in range 0->no of rows 
    for c in range(cols):              # for c in range 0 -> cols
        if image_matrix[r,c] == 0:
            image_matrix[r,c] = 1
        else:
            image_matrix[r,c] = 0

print(image_matrix)

#------- BEFORE -------------------------#
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
#-------- AFTER ------------------------#
[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [24]:
print("#------- BEFORE -------------------------#")
one_matrix = np.matrix(
    [
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0], 
        [0, 0, 1, 0, 0]
    ]
)
rows = one_matrix.shape[0]
cols = one_matrix.shape[1]

print(one_matrix)
print("#-------- AFTER ------------------------#")

for r in range(rows):                  # for r in range 0->no of rows 
    for c in range(cols):              # for c in range 0 -> cols
        if one_matrix[r,c] == 0:
            one_matrix[r,c] = 1
        else:
            one_matrix[r,c] = 0

print(one_matrix)

#------- BEFORE -------------------------#
[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]
#-------- AFTER ------------------------#
[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [25]:
print("#-------- TRANSPOSE ------------------------#")
print(one_matrix.T)

print("#-------- FLATTENED ------------------------#")
print(one_matrix.flatten())


#-------- TRANSPOSE ------------------------#
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
#-------- FLATTENED ------------------------#
[[1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
