# Operations to get elements or properties of an array

In [2]:
import numpy as np

In [5]:
an_array = np.arange(0,11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
first_el = an_array[0]
print(first_el)
last_el = an_array[10]
print(last_el)

0
10


In [8]:
first_five = an_array[0:5]
print(first_five)

[0 1 2 3 4]


In [9]:
last_five = an_array[6:]
print(last_five)

[ 6  7  8  9 10]


In [10]:
last_five = an_array[6::2]
print(last_five)

[ 6  8 10]


In [11]:
first_five_rev = an_array[4:0:-1]
print(first_five_rev)

[4 3 2 1]


In [13]:
last_two = an_array[-2:]
print(last_two)

[ 9 10]


Array Properties, length, min, max , average

In [14]:
print(an_array.size)

11


In [16]:
print(np.amax(an_array))
print(np.amin(an_array))
print(np.average(an_array))

10
0
5.0
