Explore what we have learned with the practical example of a list of student grades

In [1]:
import numpy as np

In [2]:
student_grades = np.array([56, 78, 98, 90, 58, 64, 67, 72, 93, 51])
print(student_grades)

[56 78 98 90 58 64 67 72 93 51]


In [3]:
class_average = np.average(student_grades)
print(class_average)

72.7


In [7]:
# highest grade in class
highest_grade = np.max(student_grades)
print(highest_grade)
#lowest grade in clasee
lowest_grade = np.min(student_grades)
print(lowest_grade)

98
51


In [10]:
# argmax is the index of the max value - so where in the array does the max value sit
print(np.argmax(student_grades))
# argmax is the index of the min value  - so where in the array does the min value sit
print(np.argmin(student_grades))

2
9


In [9]:
print(np.sort(student_grades))
print(-np.sort(-student_grades))

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [12]:
inc_grades = student_grades * 1.1
print (inc_grades)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [13]:
increased_grades = student_grades + 5
print(increased_grades)

[ 61  83 103  95  63  69  72  77  98  56]


In [14]:
print(np.sort(student_grades))
print(-np.sort(-student_grades))

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [17]:
# add value in np.array to the corresponding element in student grades
print(
    np.add(
        student_grades, np.array([1,2,3,4,5,6,7,8,9,10])
    )
)

[ 57  80 101  94  63  70  74  80 102  61]


In [20]:
# add 1 to the corresponding element in student grades
print(student_grades)
print(
    np.add(
        student_grades, np.ones([10])
    )
)

[56 78 98 90 58 64 67 72 93 51]
[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]
